# Generated by Django 4.0.4 on 2022-04-28 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidents',
            name='accident_number',
        ),
    ]
