# Generated by Django 4.0.4 on 2022-04-28 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_accidents_accident_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_number', models.IntegerField(null=True)),
                ('accidents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number', to='home.accidents')),
            ],
            options={
                'verbose_name_plural': 'Accident Number',
            },
        ),
    ]
